---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system-sops
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
  - name: flux-system-charts
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/overlays/dev/flux-system/sops
  prune: true
  validation: client
