---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../base/flux-system/charts
- ./aad-pod-identity-charts.yaml
- ./azuredisk-csi-driver-charts.yaml
- ./csi-secrets-store-provider-azure.yaml