---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aad
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.pomerium.io
      chart: aad-pod-identity
      version: 3.0.0
      sourceRef:
        kind: HelmRepository
        name: aad-pod-identity
        namespace: flux-system
  releaseName: aad-pod-identity
  targetNamespace: kube-system
  values:
    installCRDs: true

