---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: linkerd-stable
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://helm.linkerd.io/stable
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: linkerd-edge
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://helm.linkerd.io/edge