---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: osm
  namespace: osm-system
spec:
  interval: 5m
  chart:
    spec:
      chart: osm
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: osm
        namespace: flux-system
      version: 0.6.0-rc.1
  releaseName: osm
  targetNamespace: osm-system
  test:
    enable: false # Enable helm test
  install:
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  rollback:
    timeout: 1m
    cleanupOnFail: true
  timeout: 10m 
  values:
    OpenServiceMesh:
      deployPrometheus: false
      enablePrometheusScraping: true
      deployGrafana: false
      enableFluentbit: false
      deployJaeger: false
