---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: osm-controller
  namespace: osm-system
  labels:
    app.kubernetes.io/instance: osm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: osm
    # helm.sh/chart: osm-0.5.0
    release: kube-prometheus-stack
spec:
  endpoints:
  - interval: 30s
    port: "7070"
  jobLabel: k8s-app
  selector:
    matchLabels:
      app.kubernetes.io/instance: osm
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: osm
      # helm.sh/chart: osm-0.5.0
